# -*- coding: utf-8 -*-
"""modifications to csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TR_Of5dZGlo3ljQn-O71pw-bj5sla_M5
"""

import pandas as pd
import cv2

df = pd.read_csv('/content/FileList (1).csv')

df.head()

df.shape[0]

# Using DataFrame.insert() to add a column
df.insert(2, "ESV", 0)

print(df)

df.insert(3, "EDV", 0)

print(df)

df.insert(4, "FrameHeight", 112)

print(df)

df.insert(5, "FrameWidth", 112)

print(df)

df.drop(['Sex', 'Age', 'Weight', 'Height'], axis=1)

print(df)

df.drop(['Sex', 'Age', 'Weight', 'Height'], inplace=True, axis=1)

print(df)

import cv2
cap = cv2.VideoCapture('/content/CR3dca6aa-CR3dcb3af-000043.avi')
length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
print(length)

cap = cv2.VideoCapture('/content/CR3dca6aa-CR3dcb3af-000043.avi')
fps = int(cap.get(cv2.CAP_PROP_FPS))
print(fps)

!unzip -q A4C.zip

!rm A4C.zip

df.to_csv('/content/Fileee.csv', index = False)

df.insert(6, "FPS", 0)

print(df)

df.insert(7, "NumberOfFrames", 0)

print(df)

df.to_csv('/content/Fileooo.csv', index = False)

df.drop(['FPS', 'NumberOfFrames'], inplace=True, axis=1)

print(df)

df.insert(6, "FPS", 50)

df.insert(7, "NumberOfFrames", 200)

print(df)

df2 = pd.read_csv('/content/VolumeTracings.csv')

df2.head()

df.insert(2, "X2", 0)

print(df)

df.drop(['X2'], inplace=True, axis=1)

print(df)

df.to_csv('/content/FileL.csv', index = False)

df2.insert(2, "X2", 0)

print(df2)

df2.drop(['X2'], inplace=True, axis=1)

df2.insert(3, "X2", 0)

df2.insert(4, "Y2", 0)

print(df)

print(df2)

df2.columns = df2.columns.str.replace("X", "X1")

print(df2)

df2.columns = df2.columns.str.replace("Y", "Y1")

print(df2)

df2.drop(['X12', 'Y12'], inplace=True, axis=1)

print(df2)

df2.insert(3, "X2", 0)
df2.insert(4, "Y2", 0)

print(df2)

df2.to_csv('/content/VolumeTracingss.csv', index = False)

df2.fillna(0, inplace=True)

df2.replace('No Diastolic', 0, inplace=True)

df2.replace('No Systolic', 0, inplace=True)

df2.to_csv('/content/VolumeTracingsss.csv', index = False)