# -*- coding: utf-8 -*-
"""Ultimate Copy of UltraSwin Test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yBEhzIN53F86_sGveBeoi65oVF-TQlPG

# Persiapan

## Menyiapkan Dataset

### Download dataset

Instalasi gdown untuk mendownload file dari Google Drive
"""

!pip install gdown

"""Download dataset"""

!gdown 1Pxo4tlnQnaFYFEKgk9n3KpDAx9DHA8SP

"""### Extract Dataset

Harap menunggu beberapa saat, proses ekstraksi dataset memakan waktu kurang lebih 4 menit.
"""

!unzip -q EchoNet-Dynamic.zip

"""Hapus file EchoNet-Dynamic.zip"""

!rm EchoNet-Dynamic.zip

"""## Clone Project"""

!git clone https://github.com/lhfazry/UltraSwin

"""## Pindah Direktory ke UltraSwin"""

# Commented out IPython magic to ensure Python compatibility.
# %cd UltraSwin

"""## Instalasi Library"""

!pip install -r requirements_pip.txt

"""# Test UltraSwin-base

## Download Pre-trained Model
"""

!gdown 1ANB1NdKW8trQ9UvwtToN8z6cTnuv2Ii4

"""## Melakukan Test"""

# Commented out IPython magic to ensure Python compatibility.
# %run main.py \
    --mode=test \
    --data_dir=/content/EchoNet-Dynamic \
    --ckpt_path=UltraSwin-base-epoch=19-step=17920.ckpt \
    --batch_size=8 \
    --num_workers=4 \
    --accelerator=gpu \
    --variant=base

"""# Test UltraSwin-small

## Download Pre-trained Model
"""

!gdown 14RT5eYfsBd7EF0aIlcuaODDFGhzU8mB1

"""## Melakukan Test"""

# Commented out IPython magic to ensure Python compatibility.
# %run main.py \
    --mode=test \
    --data_dir=/content/EchoNet-Dynamic \
    --ckpt_path=UltraSwin-small-epoch=19-step=8960.ckpt \
    --batch_size=8 \
    --num_workers=4 \
    --accelerator=gpu \
    --variant=small