# -*- coding: utf-8 -*-
"""UltraSwin Test for pediatrics

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k3Tsu1c5__hDS8kME4xZx_cYcDI8oGR2

# Persiapan

## Menyiapkan Dataset

### Download dataset

Instalasi gdown untuk mendownload file dari Google Drive
"""

!pip install gdown

from google.colab import drive
drive.mount('/content/drive')

"""Download dataset"""

!gdown 1LFxNbvbHEKEuLcCtpMNeG3B62LIh7fNe

"""### Extract Dataset

Harap menunggu beberapa saat, proses ekstraksi dataset memakan waktu kurang lebih 4 menit.
"""

!unzip -q A4C.zip

"""Hapus file EchoNet-Dynamic.zip"""

!rm A4C.zip

"""## Clone Project"""

!git clone https://github.com/lhfazry/UltraSwin

"""## Pindah Direktory ke UltraSwin"""

# Commented out IPython magic to ensure Python compatibility.
# %cd UltraSwin

"""## Instalasi Library"""

!pip install -r requirements_pip.txt

"""# Test UltraSwin-base"""

!pip install pytorch_lightning==1.6.4

"""## Download Pre-trained Model"""

!gdown 1ANB1NdKW8trQ9UvwtToN8z6cTnuv2Ii4

"""## Melakukan Test"""

# Commented out IPython magic to ensure Python compatibility.
# %run main.py \
    --mode=test \
    --data_dir=/content/EchoNet-Dynamic \
    --ckpt_path=UltraSwin-base-epoch=19-step=17920.ckpt \
    --batch_size=8 \
    --num_workers=4 \
    --accelerator=gpu \
    --variant=base

"""# Test UltraSwin-small

## Download Pre-trained Model
"""

!gdown 14RT5eYfsBd7EF0aIlcuaODDFGhzU8mB1

"""## Melakukan Test"""

# Commented out IPython magic to ensure Python compatibility.
# %run main.py \
    --mode=test \
    --data_dir=/content/EchoNet-Dynamic \
    --ckpt_path=UltraSwin-small-epoch=19-step=8960.ckpt \
    --batch_size=8 \
    --num_workers=4 \
    --accelerator=gpu \
    --variant=small